# Generated by Django 3.2 on 2023-11-11 13:57

from django.db import migrations, models
import psqlextra.indexes.unique_index


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_filmwork_file_path'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personfilmwork',
            name='role',
            field=models.CharField(choices=[('DR', 'Director'), ('SW', 'Screenwriter'), ('AC', 'Actor')], default='AC', max_length=2, verbose_name='role'),
        ),
        migrations.AddIndex(
            model_name='filmwork',
            index=psqlextra.indexes.unique_index.UniqueIndex(fields=['title', 'description'], name='film_work_title_abf8d4_idx'),
        ),
        migrations.AddIndex(
            model_name='person',
            index=models.Index(fields=['full_name'], name='person_full_na_058eac_idx'),
        ),
        migrations.AddConstraint(
            model_name='genrefilmwork',
            constraint=models.UniqueConstraint(fields=('genre', 'film_work'), name='soooome_name'),
        ),
        migrations.AddConstraint(
            model_name='personfilmwork',
            constraint=models.UniqueConstraint(fields=('person_id', 'film_work_id'), name='CRINGE'),
        ),
    ]
