version: '3.8'

services:

  postgres:
    image: postgres:16.1
    container_name: admin-postgres
    volumes: 
      - db:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}

  admin_panel:
    container_name: admin-panel
    build:
      context: ./admin
    command: >
      sh -c "python manage.py collectstatic --noinput &&
             python manage.py migrate &&
             gunicorn --bind 0.0.0.0:8000 config.wsgi:application"
    volumes:
      - ${ADMIN_DIR_PATH}:/app
    depends_on:
      - postgres
    env_file:
      - .env

  billing-api:
    build: ./billing-api
    container_name: billing-api
    command: >
      sh -c "alembic upgrade head &&
             uvicorn --reload --host 0.0.0.0 --port 8001 main:app"
    depends_on:
      - postgres
    env_file:
      - .env

  worker:
    build: ./billing-api
    container_name: celery-workers
    command: celery -A tasks.celery worker --loglevel=info
    depends_on:
      - billing-api
      - redis
    env_file:
      - .env

  redis:
    image: redis:7

  nginx:
    container_name: admin-nginx
    image: nginx:1.25.3
    volumes:
      - ./config/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - admin_panel
      - billing-api
    ports:
      - "81:81"

volumes:
  db:
