"""update refund model

Revision ID: 58bb7feec43a
Revises: 4f837f4a965f
Create Date: 2024-01-31 09:31:25.271748

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '58bb7feec43a'
down_revision: Union[str, None] = '4f837f4a965f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('refund', sa.Column('refund_id', sa.UUID(), nullable=False))
    op.alter_column('refund', 'payment_id',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('refund', 'amount',
               existing_type=sa.INTEGER(),
               type_=sa.Numeric(precision=6, scale=2),
               nullable=False)
    op.alter_column('refund', 'status',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('refund', 'status',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('refund', 'amount',
               existing_type=sa.Numeric(precision=6, scale=2),
               type_=sa.INTEGER(),
               nullable=True)
    op.alter_column('refund', 'payment_id',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_column('refund', 'refund_id')
    # ### end Alembic commands ###
