version: '3.7'

services:

  postgres_db:
    image: postgres:13
    container_name: admin-postgres
    volumes: 
      - db:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=app
      - POSTGRES_PASSWORD=123qwe
      - POSTGRES_DB=movies_database
    networks:
      - admin_panel

  django_gunicorn:
    container_name: admin-django-gunicorn
    volumes:
      - /Users/Danya/PycharmProjects/AdminPanel/django_project:/app
    env_file:
      - .env
    build:
      context: .
    networks:
      - admin_panel

  nginx:
    image: nginx:stable
    container_name: admin-nginx
    volumes:
      - ./config/nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "81:81"
    depends_on:
      - django_gunicorn
    networks:
      - admin_panel

networks:
  admin_panel:

volumes:
  db:

